# Generated by Django 5.1.7 on 2025-03-21 12:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("per_guest", models.BooleanField(default=False)),
                ("options", models.JSONField()),
                ("tiers_allowed", models.JSONField(default=list)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField(auto_now_add=True)),
                ("event_date", models.DateField()),
                ("custom_venue", models.BooleanField(default=False)),
                (
                    "venue_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Minimal", "Minimal"),
                            ("Medium", "Medium"),
                            ("Luxury", "Luxury"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("venue_description", models.TextField(blank=True, null=True)),
                ("cus_name", models.CharField(max_length=255)),
                ("cus_email", models.EmailField(max_length=254)),
                (
                    "cus_ph",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10}$", message="Phone number must be 10 digits."
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("customer_request", models.TextField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatbotQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.TextField()),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords for matching",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_available", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("desc", models.TextField(default="No description provided")),
                ("available_dates", models.JSONField(default=list)),
                (
                    "estimated_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Starting price in INR, final price depends on customization.",
                        max_digits=12,
                    ),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="events/")),
                (
                    "event_type",
                    models.CharField(default="Not specified", max_length=50),
                ),
                (
                    "event_duration",
                    models.CharField(default="Not specified", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Minimal", "Minimal"),
                            ("Medium", "Medium"),
                            ("Premium", "Premium"),
                        ],
                        default="Minimal",
                        max_length=10,
                    ),
                ),
                (
                    "guest_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("venue_size", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "selected_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "venue_subtier",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("custom_venue_description", models.TextField(blank=True, null=True)),
                ("add_ons", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "full_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("pincode", models.CharField(blank=True, max_length=20, null=True)),
                ("place_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
