# Generated by Django 5.1.4 on 2024-12-19 11:25

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cus_name", models.CharField(max_length=55)),
                ("cus_ph", models.CharField(max_length=12)),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
                ("venue", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("booking_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submitted_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("desc", models.TextField(default="no description provided")),
                ("event_date", models.DateField(default=django.utils.timezone.now)),
                ("location", models.CharField(default="not specified", max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("img", models.ImageField(blank=True, upload_to="events/")),
                (
                    "event_type",
                    models.CharField(default="not specified", max_length=50),
                ),
                (
                    "event_duration",
                    models.CharField(default="not specified", max_length=50),
                ),
                ("itinerary", models.JSONField(default=list)),
            ],
        ),
    ]
