# Generated by Django 5.1.4 on 2024-12-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
