# Generated by Django 5.1.4 on 2024-12-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0002_event_is_available_alter_event_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cus_email",
            field=models.EmailField(default="default@example.com", max_length=254),
        ),
    ]
