# Generated by Django 5.1.7 on 2025-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="available_dates",
        ),
        migrations.AddField(
            model_name="event",
            name="available_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
