# Generated by Django 5.1.7 on 2025-03-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0003_remove_event_available_dates_event_available_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlocation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventlocation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
