# Generated by Django 5.1.4 on 2024-12-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0006_remove_booking_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="event_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventapp.event"
            ),
        ),
    ]
