# Generated by Django 5.1.4 on 2025-01-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0007_alter_booking_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="event_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="eventapp.event",
            ),
        ),
    ]
