# Generated by Django 5.1.4 on 2025-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0010_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
