# Generated by Django 5.1.4 on 2025-02-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0011_booking_total_amount"),
        ("paymentapp", "0007_payment_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_payment",
                to="paymentapp.payment",
            ),
        ),
    ]
