# Generated by Django 5.1.4 on 2025-03-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0012_booking_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCustomization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue_size",
                    models.CharField(
                        choices=[
                            ("Small", "Small"),
                            ("Medium", "Medium"),
                            ("Large", "Large"),
                        ],
                        default="Small",
                        max_length=10,
                    ),
                ),
                (
                    "catering",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Buffet", "Buffet"),
                            ("Multi-Course", "Multi-Course"),
                            ("Custom", "Custom Menu"),
                        ],
                        default="Standard",
                        max_length=20,
                    ),
                ),
                (
                    "decorations",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Themed", "Themed"),
                            ("Luxury", "Luxury"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                (
                    "entertainment",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("DJ", "DJ"),
                            ("Live Band", "Live Band"),
                            ("Projector", "Projector"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "seating_arrangement",
                    models.CharField(
                        choices=[
                            ("Formal", "Formal"),
                            ("Casual", "Casual"),
                            ("Custom", "Custom"),
                        ],
                        default="Formal",
                        max_length=10,
                    ),
                ),
                (
                    "photography",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Basic", "Basic"),
                            ("Professional", "Professional"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
                (
                    "lighting_effects",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Themed", "Themed"),
                            ("Premium", "Premium"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization",
                        to="eventapp.booking",
                    ),
                ),
            ],
        ),
    ]
