# Generated by Django 5.1.4 on 2025-03-12 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0013_eventcustomization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="event_name",
            new_name="event",
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="tier",
            field=models.CharField(
                choices=[
                    ("Minimal", "Minimal"),
                    ("Medium", "Medium"),
                    ("Premium", "Premium"),
                ],
                default="Minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="cus_ph",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", message="Phone number must be 10 digits."
                    )
                ],
            ),
        ),
    ]
