# Generated by Django 5.1.4 on 2025-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0014_rename_event_name_booking_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="venue",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
