# Generated by Django 5.1.4 on 2025-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0016_chatbotqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="custom_venue",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="venue_size",
            field=models.CharField(
                blank=True,
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Small",
                max_length=10,
                null=True,
            ),
        ),
    ]
