# Generated by Django 5.1.4 on 2025-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0017_booking_custom_venue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
