# Generated by Django 5.1.4 on 2025-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0018_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="audio_visual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="event_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="medical_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="post_event_media",
            field=models.BooleanField(default=False),
        ),
    ]
