# Generated by Django 5.1.4 on 2025-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0019_eventcustomization_audio_visual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="cleanup_service",
            field=models.BooleanField(default=False),
        ),
    ]
