# Generated by Django 5.1.7 on 2025-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0020_eventcustomization_cleanup_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="selected_location",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
