# Generated by Django 5.1.7 on 2025-03-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0021_eventcustomization_selected_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
