# Generated by Django 5.1.7 on 2025-03-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0023_eventlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="selected_options",
            field=models.JSONField(default=dict),
        ),
    ]
