# Generated by Django 5.1.7 on 2025-03-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0024_eventcustomization_selected_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="addon_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
