# Generated by Django 5.1.7 on 2025-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0025_eventcustomization_addon_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("is_per_guest", models.BooleanField(default=False)),
                ("options", models.JSONField()),
                ("tiers_allowed", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name="eventcustomization",
            name="addon_details",
        ),
        migrations.RemoveField(
            model_name="eventcustomization",
            name="selected_options",
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="catering",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="decorations",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="entertainment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="guest_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="lighting_effects",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="photography",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="seating_arrangement",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="selected_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="tier",
            field=models.CharField(
                choices=[
                    ("Minimal", "Minimal"),
                    ("Medium", "Medium"),
                    ("Premium", "Premium"),
                ],
                default="Minimal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="venue_size",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
