# Generated by Django 5.1.4 on 2025-03-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0026_addon_remove_eventcustomization_addon_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="addon_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="eventcustomization",
            name="selected_options",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="catering",
            field=models.CharField(
                choices=[
                    ("Standard", "Standard"),
                    ("Buffet", "Buffet"),
                    ("Multi-Course", "Multi-Course"),
                    ("Custom", "Custom Menu"),
                ],
                default="Standard",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="decorations",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Luxury", "Luxury"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="entertainment",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("DJ", "DJ"),
                    ("Live Band", "Live Band"),
                    ("Projector", "Projector"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="lighting_effects",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Premium", "Premium"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="photography",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Basic", "Basic"),
                    ("Professional", "Professional"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="seating_arrangement",
            field=models.CharField(
                choices=[
                    ("Formal", "Formal"),
                    ("Casual", "Casual"),
                    ("Custom", "Custom"),
                ],
                default="Formal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="selected_location",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="tier",
            field=models.CharField(
                choices=[
                    ("Minimal", "Minimal"),
                    ("Medium", "Medium"),
                    ("Premium", "Premium"),
                ],
                default="Minimal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="venue_size",
            field=models.CharField(
                blank=True,
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default="Small",
                max_length=10,
                null=True,
            ),
        ),
    ]
