# Generated by Django 5.1.4 on 2025-03-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0027_eventcustomization_addon_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlocation",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location",
                to="eventapp.booking",
            ),
        ),
    ]
