# Generated by Django 5.1.4 on 2025-03-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0028_eventlocation_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcustomization",
            name="table_arrangements",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Premium", "Premium"),
                ],
                default="Basic",
                max_length=20,
            ),
        ),
    ]
