# Generated by Django 5.1.4 on 2025-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0029_eventcustomization_table_arrangements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventcustomization",
            name="post_event_media",
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="catering",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Standard", "Standard"),
                    ("Buffet", "Buffet"),
                    ("Multi-Course", "Multi-Course"),
                    ("Custom", "Custom Menu"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="decorations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Luxury", "Luxury"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="entertainment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("DJ", "DJ"),
                    ("Live Band", "Live Band"),
                    ("Projector", "Projector"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="lighting_effects",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Premium", "Premium"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="photography",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Basic", "Basic"),
                    ("Professional", "Professional"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="seating_arrangement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Formal", "Formal"),
                    ("Casual", "Casual"),
                    ("Custom", "Custom"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventcustomization",
            name="table_arrangements",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("Basic", "Basic"),
                    ("Themed", "Themed"),
                    ("Premium", "Premium"),
                ],
                default="None",
                max_length=20,
                null=True,
            ),
        ),
    ]
