# Generated by Django 5.1.4 on 2024-12-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventapp", "0004_booking_admin_notes_booking_customer_request_and_more"),
        ("paymentapp", "0002_payment_simulation_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="event_booking",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="simulation_result",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="eventapp.booking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="proof_of_payment",
            field=models.ImageField(default="no proof provided", upload_to="payments/"),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Verified", "Verified"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
