# Generated by Django 5.1.4 on 2024-12-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "paymentapp",
            "0003_remove_payment_amount_remove_payment_event_booking_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
