# Generated by Django 5.1.4 on 2024-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paymentapp", "0006_alter_payment_proof_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="pic/qr_codes/"),
        ),
    ]
