# Generated by Django 5.1.4 on 2025-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_changerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="new_value",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="request_type",
            field=models.CharField(
                choices=[("Date", "Date"), ("Venue", "Venue")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
