# Generated by Django 5.1.4 on 2025-01-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_alter_changerequest_new_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
